#Notification-개발/8157 Add documents
TOAST-DOCS/notification-hub pull request #1
Opened 2024-10-13 13:57 UTC by gimbimloki

### Dooray Issue

* https://nhnent.dooray.com/project/tasks/3909784012070578329

### Comments
* 개요, 서비스 정책, 사용 전 준비 및 제한 사항, 콘솔 가이드 등
* API 가이드는 이번 PR에서 제외

#### 사용자 가이드 예상 구조
```
* 개요
- 서비스 정책
	* 개인 정보 처리 안내
	* 이용 약관
	* 본인 인증
	* 최초 사용자 제한
- 상품 사용 전 준비 및 안내 사항
	* SMS
		* 발신 번호 사전 등록제 시행 안내
		* 발신 번호 변작/변조 금지 안내
		* 수신 실패 원인
			* 번호 도용 문자 차단 서비스 안내
			* 통신사 스팸 차단 서비스 안내
		* 광고 문자 발송을 위한 의무 사항
		* 080 수신거부 번호 명시 안내
	* 국제 SMS
		* 국가별 발신 번호 정책
		* 발송 정책
		* 과금 정책
		* 국제 SMS 물량 펌핑 현상
		* 전송 가능 국가 
	* 알림톡, 친구톡
		* 카카오 비즈니스와 발신프로필 생성
	* RCS
		* 브랜드 생성
	* 이메일
		* 발신 도메인 안내
		* SPF, DKIM, DMARC 안내
	* 푸시
		* FCM, APNS, ADM 인증서 발급 안내
* 콘솔 사용 가이드
	* 발송
	* 발송 조회
	* 주소록
	* 템플릿
	* 플로우
	* 통계
	* 상세 설정
* API v1.0 사용 가이드
	* 메시지 API
	* 연락처 수신 결과 API
	* 템플릿 API
	* 플로우 API
* 릴리스 노트
```

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +### 카테고리
@gimbimloki 템플릿 하위 헤더 확인 부탁드립니다. h2 없이 바로 h3로 이어지네요.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +### 플로우
@gimbimloki 발송 하위 헤더도 확인 부탁드립니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +* 요금은 연결된 메시지 건수에 따라 과금됩니다.
@gimbimloki 국제 SMS는 최대 제한 글자수가 추가되지 않아도 괜찮을까요? 
사용 전 준비 및 제한 사항 > 국제 SMS 에 포함되어 있긴 하네요.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +    * 메시지 타입(SMS/LMS/MMS/AUTH), 발송 타입(일반/대량/태그), 발신 번호, 수신번호, 제목, 본문, 첨부파일
@gimbimloki 발송 타입이 제외되어야합니다. (hub 발송은 sms 내부적으로 따로 발송 타입을 구분하지 않습니다)

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +    * 제한 시간 해제 후 재발송
@gimbimloki RCS는 현재 실패 처리만 가능합니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +| 전체 | 메시지 | 요청됩(REQUESTED), 취소됨(CANCELED), 발송 성공(SENT), 발송 실패(SEND_FAILED), 수신(DELIVERED), 수신 실패(DELIVERY_FAILED) | 발송 과정에서 발생한 이벤트입니다. |
@gimbimloki 요청됨 오타 있습니다~

2024-10-14 01:44 UTC, aka1yuta commented on ko/preconditions/preconditions-international-sms.md
> +* 각 DLR은 메시지 상태와 결과 코드를 제공하며, 이를 통해 특정 SMS의 전송 상태를 알 수 있으나 정확성을 절대적으로 보장할 수는 없으며 통신사 및 단말기 상황에 따라 메시지 상태 및 결과 코드가 값이 NULL 일 수 있습니다.
@gimbimloki hub는 DLR이 아직 지원되지 않습니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/service-policy/identity-verification.md
> +  * 본인 인증을 하지 않으면 **발신 번호 사전 등록 탭** 이외의 기능은 모두 비활성화됩니다.
@gimbimloki 서비스 명 변경이 필요합니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/service-policy/new-user-restrictions.md
> +* 발송량 제한은 SMS/LMS/MMS/국제SMS 종류와 상관 없이 전체 문자 메시지 발송 건수를 포함한 한도입니다.
@gimbimloki SMS 상품과 hub 상품의 발송이 모두 합쳐진 건수를 명시하면 어떨까요

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
@gimbimloki 허브 콘솔에서 명칭이 `월 발송 건수`로 변경되어 반영이 필요합니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +    * [통신사 스팸 차단 서비스 가이드 바로가기](./service-policy/service-policy-sms#spam-number)
@gimbimloki 가이드 링크 변경이 필요합니다.

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +* 메시지 타입을 선택합니다. 타입별 상세 가이드는 [친구톡 발송 지원 타입](https://docs.nhncloud.com/ko/Notification/KakaoTalk%20Bizmessage/ko/friendtalk-overview/#_3)에서 확인하세요.
@gimbimloki ktb의 가이드 링크로 연결되나요?

2024-10-14 01:44 UTC, aka1yuta commented on ko/console-guide.md
> +* 국제 SMS 발송 기능 이용 전 반드시 [[국제 SMS 서비스 정책]](./service-policy/service-policy-international-sms)을 확인합니다.
@gimbimloki 가이드 링크 변경이 필요합니다.

2024-10-14 01:53 UTC, sanggu-jeong commented on ko/overview.md
> +* 메시지 채널 별로 페이지가 구분되어 있어거나 사용 편의성을 위해 기능 단위로 묶어서 페이지를 제공합니다.
있어거나 - 오타인듯 합니다.

2024-10-14 01:57 UTC, sanggu-jeong commented on ko/overview.md
> +* 직접 입력, 주소록에서 선택, 주소록 그룹 선택, 파일 업로드로 수신자를 추가할 수 있습니다.
주소록 그룹 선택은 이번에 스펙에서 제외되지 않았나요?

2024-10-14 02:00 UTC, sanggu-jeong commented on ko/preconditions/preconditions-email.md
> +* yahoo.com
hub에서는 도메인 인증이 필수여서 미인증시 모두 발송이 되지않고
gmail.com, yahoo.com 은 SPF, DKIM, DMARC를 모두 등록해야 발송이 가능합니다.
이부분 수정이 필요할듯 합니다.

2024-10-14 06:24 UTC, sanggu-jeong commented on ko/preconditions/preconditions-ktb.md
> +* [발신프로필 관리 바로가기](./console-guide#ktb-sender-profile)에서 확인할 수 있습니다.
여기경로는 나중에 변경되는걸까요?
console-guide와 현재 파일이 동일 디렉토리에 있지 않아 매핑되지 않을듯 해서요

2024-10-14 06:27 UTC, sanggu-jeong commented on ko/preconditions/preconditions-rcs.md
> +    * 텍스트/이미지 템플릿 한해서 등록이 가능합니다. [[발송 지원 타입]](./overview)
여기 링크가 잘 연결되어 있는걸까요?

2024-10-14 06:32 UTC, sanggu-jeong commented on ko/preconditions/preconditions-rcs.md
> +2. 대화방 등록이 완료(승인)되었다면, **Notification** > **RCS Bizmessage** > **RCS Bizmessage 관리** > **브랜드 관리** 탭에서 NHN Cloud 콘솔에 연동이 가능합니다.
여기는 Hub 메뉴 경로로 수정해야할듯 합니다.

2024-10-14 06:33 UTC, sanggu-jeong commented on ko/preconditions/preconditions-rcs.md
> +2. 대화방 등록이 완료(승인)되었다면, **Notification** > **RCS Bizmessage** > **RCS Bizmessage 관리** > **브랜드 관리** 탭에서 NHN Cloud 콘솔에 연동이 가능합니다.
아 아래에 관련내용이 있어서 이건 삭제해도 되나요?

2024-10-14 06:37 UTC, sanggu-jeong commented on ko/preconditions/preconditions-sms.md
> +* 타인(또는 타사) 발신번호를 사용하는 경우 <a href="https://www.msit.go.kr/bbs/view.do?sCode=user&mId=108&mPid=103&bbsSeqNo=83&nttSeqNo=1259891" target="_blank">(미래창조과학부고시 제2015-32호) 거짓으로 표시된 전화번호로 인한 이용자의 피해 예방 등에 관
![image](https://github.com/user-attachments/assets/c4e1a179-8c51-4ccf-829b-ef826c481da7)
링크가 깨졌네요

2024-10-14 06:39 UTC, sanggu-jeong commented on ko/service-policy/identity-verification.md
> +<b>Notification Hub를 이용하려면 [콘솔 > 본인 인증 > 발신 번호 등록 및 명의자 인증]에서 발신 번호를 사전에 등록한 후 사용할 수 있습니다. (전기통신사업법 관련 고시 준수)</b>
메뉴 경로가 허브와 맞지 않는것 같네요

2024-10-14 06:40 UTC, sanggu-jeong commented on ko/service-policy/identity-verification.md
> +  * 본인 인증을 하지 않으면 **발신 번호 사전 등록 탭** 이외의 기능은 모두 비활성화됩니다.
**발신 번호 사전 등록 탭**
탭이름도 hub에 맞게 변경되어야 합니다.

2024-10-14 06:41 UTC, sanggu-jeong commented on ko/service-policy/terms-of-use.md
> +    <title>Notification 이용약관</title>
이건 Notification으로 가는게 맞는거죠?

2024-10-14 06:58 UTC, sanggu-jeong commented on ko/console-guide.md
> +| 친구톡 | 메시지 | 요청됩(REQUESTED), 취소됨(CANCELED), 발송 성공(SENT), 발송 실패(SEND_FAILED), 수신(DELIVERED), 수신 실패(DELIVERY_FAILED) | |
발송 성공이니 수신도 수신 성공이 좋지 않을까요?

2024-10-14 23:13 UTC, gimbimloki commented on ko/preconditions/preconditions-email.md
> +* yahoo.com
@sanggu-jeong `#### SPF, DKIM, DMARC 미인증 시 발송 제한 대상 도메인` 이렇게 바꾸면 될까요?

2024-10-14 23:15 UTC, sanggu-jeong commented on ko/preconditions/preconditions-email.md
> +* yahoo.com
@gimbimloki 
네 그러면 될듯합니다!

2024-10-15 01:07 UTC, gimbimloki commented on ko/service-policy/terms-of-use.md
> +    <title>Notification 이용약관</title>
@sanggu-jeong 일단 이렇게 해놓고, 승원 선임님께 검수 받아보면 될 것 같습니다.

2024-10-15 01:11 UTC, gimbimloki commented on ko/console-guide.md
> +### 카테고리
```
## 카테고리
## 템플릿
### 알림톡 템플릿
### 알림톡 템플릿 버튼
### 템플릿 검수
...
```

@aka1yuta 이런식으로 수정하겠습니다.

2024-10-15 01:24 UTC, gimbimloki commented on ko/console-guide.md
> +### 플로우
@aka1yuta 전체적으로 수정했습니다.

2024-10-15 01:30 UTC, gimbimloki commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
@aka1yuta "국제 SMS 메시지 발송 설정"에서 "국제 SMS 발송"을 사용으로 하면 알림도 가는거죠?

2024-10-15 01:31 UTC, gimbimloki commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
```
* 월 발송 건수 및 임계치 알림
    * **월 발송 건수**는 월 1,000건이 기본이며, 최대 10,000건까지 적용 가능합니다.
    * **월 발송 건수**는 보조 기능으로 임계치 초과에 대한 탐지가 실시간으로 반영되지 않을 수 있습니다. 보조 기능의 일부 오차에 대해 NHN Cloud는 책임을 지지 않으니 주의해서 사용하시기 바랍니다.
    * **국제 SMS 발송**을 **사용**으로 설정하면 **월 발송 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
```

이렇게 변경 합니다.

2024-10-15 01:32 UTC, gimbimloki commented on ko/console-guide.md
> +* 요금은 연결된 메시지 건수에 따라 과금됩니다.
@aka1yuta 아래에 과금표 추가했습니다. 간단한 내용이라 링크 보다 직접 추가했습니다.

2024-10-15 01:32 UTC, gimbimloki commented on ko/console-guide.md
> +    * 메시지 타입(SMS/LMS/MMS/AUTH), 발송 타입(일반/대량/태그), 발신 번호, 수신번호, 제목, 본문, 첨부파일
@aka1yuta 수정했습니다.

2024-10-15 01:32 UTC, gimbimloki commented on ko/console-guide.md
> +    * 제한 시간 해제 후 재발송
@aka1yuta 수정했습니다.

2024-10-15 01:32 UTC, gimbimloki commented on ko/service-policy/new-user-restrictions.md
> +* 발송량 제한은 SMS/LMS/MMS/국제SMS 종류와 상관 없이 전체 문자 메시지 발송 건수를 포함한 한도입니다.
@aka1yuta Notification Hub와 SMS 합산한다고 수정했습니다.

2024-10-15 01:33 UTC, gimbimloki commented on ko/console-guide.md
> +    * [통신사 스팸 차단 서비스 가이드 바로가기](./service-policy/service-policy-sms#spam-number)
@aka1yuta 수정했습니다.

2024-10-15 01:33 UTC, gimbimloki commented on ko/console-guide.md
> +* 메시지 타입을 선택합니다. 타입별 상세 가이드는 [친구톡 발송 지원 타입](https://docs.nhncloud.com/ko/Notification/KakaoTalk%20Bizmessage/ko/friendtalk-overview/#_3)에서 확인하세요.
@aka1yuta Hub 문서로 링크 변경했습니다.

2024-10-15 01:33 UTC, gimbimloki commented on ko/console-guide.md
> +* 국제 SMS 발송 기능 이용 전 반드시 [[국제 SMS 서비스 정책]](./service-policy/service-policy-international-sms)을 확인합니다.
@aka1yuta 수정했습니다.

2024-10-15 01:33 UTC, gimbimloki commented on ko/console-guide.md
> +| 친구톡 | 메시지 | 요청됩(REQUESTED), 취소됨(CANCELED), 발송 성공(SENT), 발송 실패(SEND_FAILED), 수신(DELIVERED), 수신 실패(DELIVERY_FAILED) | |
@aka1yuta 수정했습니다.

2024-10-15 01:36 UTC, sanggu-jeong commented on ko/preconditions/preconditions-email.md
> +* yahoo.com
@gimbimloki 
이 부분이 아직 수정안되었네요

2024-10-15 01:37 UTC, sanggu-jeong approved these changes
https://github.com/TOAST-DOCS/notification-hub/pull/1/files#diff-6617d5205f8b231699b23ac04d2cc641bf36431e33b20ab52b09fb6ee4f1bb2dR47
위 내용 아직 수정 안된부분이 있습니다.
👍

2024-10-15 01:55 UTC, gehwan96 commented on ko/overview.md
> +* 발송을 위한 메시지 작성 시 수신 시 표시될 메시지의 내용에 대한 미리 보기를 제공합니다.
@gimbimloki 
발송을 위한 메시지 작성 시 수신자에게 표시될 메시지의 내용에 대한 미리 보기를 제공합니다는 어떤가요?

2024-10-15 01:55 UTC, gehwan96 commented on ko/overview.md
> +### 공유되는 설정과 자원
@gimbimloki 
자원 / 리소스 중 한 단어로 통일하는게 좋을 것 같습니다.

2024-10-15 01:55 UTC, gehwan96 commented on ko/preconditions/preconditions-email.md
> +* 반송률로 인해 이메일 발송이 제한된 경우 아래의 사항을 확인하십시오.
@gimbimloki 
* 반송률로 인해 이메일 발송이 제한된 경우 아래의 사항을 확인하십시오.
* 반송이 발생하는 원인에 해당하는 사항이 있는지 확인한 뒤 개선 조치를 하십시오.

=> 반송률로 인해 이메일 발송이 제한된 경우 반송이 발생하는 원인에 해당하는 사항이 있는지 확인한 뒤 개선 조치를 하십시오. 는 어떨까요?

2024-10-15 01:55 UTC, gehwan96 commented on ko/console-guide.md
> +| 친구톡 | 메시지 | 요청됩(REQUESTED), 취소됨(CANCELED), 발송 성공(SENT), 발송 실패(SEND_FAILED), 수신(DELIVERED), 수신 실패(DELIVERY_FAILED) | |
@gimbimloki 
요청됩 -> 요청됨으로 수정 부탁드립니다.

2024-10-15 02:03 UTC, Taeyoung-Kwak requested changes
VS Code markdownlint extension 사용하면 편리합니다

2024-10-15 05:31 UTC, aka1yuta commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
@gimbimloki 국제발송 설정과 임계치 알림이 기존 SMS에선 따로 설정하게 되어있는데요. hub는 알림에 대한 설정이 따로 없습니다.
이거 승원선임님한테 확인하고 정리하겠습니다.

2024-10-15 23:42 UTC, gimbimloki commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
@aka1yuta 넵, 정리하고 여기에 댓글 부탁드립니다.

2024-10-15 23:45 UTC, gimbimloki commented on ko/preconditions/preconditions-email.md
> +* 반송률로 인해 이메일 발송이 제한된 경우 아래의 사항을 확인하십시오.
@sanggu-jeong 제안해주신 내용으로 수정했습니다.

2024-10-15 23:58 UTC, gimbimloki commented on ko/overview.md
> +### 공유되는 설정과 자원
@gehwan96 자원으로 통일했습니다.

2024-10-16 00:01 UTC, gimbimloki commented on ko/overview.md
> +* 발송을 위한 메시지 작성 시 수신 시 표시될 메시지의 내용에 대한 미리 보기를 제공합니다.
@gehwan96 "메시지 작성 시 수신자에게 표시될 메시지의 내용에 대한 미리 보기를 제공합니다."으로 수정했습니다.

2024-10-18 01:32 UTC, aka1yuta commented on ko/console-guide.md
> +    * **월 제한 건수 임계치 알림**을 **사용**으로 설정하면 **자동 차단 월 제한 건수**로 설정한 값의 70%, 100% 도달 시 프로젝트 멤버 전체에게 알림 메일이 발송됩니다.
국제발송 임계치에 따른 알림은 스펙아웃으로 확인되었습니다.

2024-10-18 01:59 UTC, mpshjee commented on ko/console-guide.md
> +* MMS는 카드별로 한글, 영문 구분 없이 제목을 최대 30자, 내용을 최대 1,300자까지 입력할 수 있고, 이미지 1개, 버튼은 최대 3개까지 설정할 수 있습니다.
@gimbimloki 버튼이 최대 2개로 수정되어야할것같습니다

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +    * 위치명 및 지도 URL을 입력합니다.(ht<span>tps://</span>를 포함한 URL)
@gimbimloki span 위치 조정이 필요할것같습니다

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +도메인 보호를 비활성화 하는 경우, 다른 프로젝트에서 임의로 도메인을 사용할 수 있습니다. 모든 인증을 완료한 도메인의 경우, 다른 프로젝트에서 발송하는 메일도 동일하게 이메일 수신 서버에서 정상적으로 수신이 됩니다. 이렇게 발송된 이메일이 스팸이거나 피싱인 경우, 수신자에게 피해가 발생할 수 있고 도메인의 평판이 하락해 수신 이베일 서버에서 수신을 거부
@gimbimloki 오타 수정 필요합니다 이베일 -> 이메일

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +* 개별 메시지 채널 발송인 경우, 메시치 채널에 해당하는 연락처를 입력합니다.
@gimbimloki 오타 수정필요합니다 메시치 -> 메시지

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +        - 리소스는 리치 메시지를 생성하는 <a href="http://docs.toast.com/ko/TOAST/ko/toast-sdk/push-ios/#notification-service-extension">Notificaiton Service Extension</a> 프로젝트에 미리 추가해야 합니다.
@gimbimloki 오타 수정 필요합니다. Notificaiton -> Notification

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +        - iOS 9 이상에서 HTTP를 사용하려면 Info.plist 파일내에 ATS(App Trasport Secuirty)를 설정해야 합니다.
@gimbimloki 오타 수정 필요합니다. Trasport -> Transport

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +    * 조회 기간 설정 가능 범위은 기본, 최대 7일입니다.
@gimbimloki 오타 수정 필요합니다. 범위은 -> 범위는

2024-10-18 02:26 UTC, mpshjee commented on ko/console-guide.md
> +    * 조회 기간 설정 가능 범위은 기본, 최대 7일입니다.
@gimbimloki 오타 수정 필요합니다. 범위은 -> 범위는

2024-10-21 01:29 UTC, gimbimloki commented on ko/console-guide.md
> +    * 조회 기간 설정 가능 범위은 기본, 최대 7일입니다.
@mpshjee 수정완료했습니다.

2024-10-21 02:19 UTC, gehwan96 commented on ko/preconditions/preconditions-international-sms.md
> +# 전송 가능 국가
@gimbimloki 

https://nhnent.dooray.com/task/1585877748864896950/3918340795177133856
- 사용자가이드, 콘솔은 국가코드 오름차순으로 정렬 요청하시는 것 같습니다. 

사용자가이드는 현재 영문 기준으로 설정되어 있다고 하네요.

2024-10-21 02:20 UTC, gehwan96 approved these changes
👍 
@gimbimloki 팀장님
https://github.com/TOAST-DOCS/notification-hub/pull/1/files#r1808022280
만 수정 부탁드립니다.

2024-10-22 02:38 UTC, gimbimloki commented on ko/preconditions/preconditions-international-sms.md
> +# 전송 가능 국가
@gehwan96 수정했습니다.

2024-10-22 02:39 UTC, merged